--- 
- hosts: all
  become: yes
  tasks: 
  - name: "I want to install webserver"
    apt:
     name: apache2
     state: present
  
  - name: "I want to install tree"
    apt: 
     name: tree 
     state: present 

  - name: "copy file"
    ansible.builtin.file:
     src: /home/ubuntu/hbk
     dest: /home/ubuntu
     state: touch